/******************************************************************************/
/***         Generated by IBExpert 2012.5.19.1 09/09/2016 17:18:59          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'LOCALHOST:D:\Edson\Database\DB.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_LOGUSUARIO_ID;
SET GENERATOR GEN_LOGUSUARIO_ID TO 1;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE LOGUSUARIO (
    SEQ          INTEGER NOT NULL,
    CODUSUARIO   INTEGER,
    USUARIO      VARCHAR(15),
    EVENTO       VARCHAR(20),
    DATA         DATE,
    TABELA       VARCHAR(20),
    CAPTION      VARCHAR(40),
    CAMPOCHAVE   VARCHAR(20),
    CAMPOCHAVE1  VARCHAR(20),
    CAMPOCHAVE2  VARCHAR(20),
    HORA         VARCHAR(5),
    MOVIMENTO    VARCHAR(45),
    LOCALMOV     VARCHAR(20),
    MAQUINA      VARCHAR(40)
);

CREATE TABLE NCONTADOR (
    COLUNA  VARCHAR(255) NOT NULL,
    VALOR   INTEGER
);

CREATE TABLE PROGRAMAS (
    CODPROGRAMA   INTEGER NOT NULL,
    NOMEPROGRAMA  VARCHAR(50),
    DESCRICAO     VARCHAR(40),
    MENU          VARCHAR(40),
    ITEM          VARCHAR(40),
    SUBITEM       VARCHAR(40)
);

CREATE TABLE PROGRAMASUSUARIO (
    CODUSUARIO     INTEGER NOT NULL,
    CODPROGRAMA    INTEGER NOT NULL,
    BTNINCLUIR     INTEGER,
    BTNALTERAR     INTEGER,
    BTNEXCLUIR     INTEGER,
    BTNVISUALIZAR  INTEGER,
    BTNIMPRIMIR    INTEGER,
    BTNCHAVE1      INTEGER,
    BTNCHAVE2      INTEGER,
    BTNCHAVE3      INTEGER,
    BTNCHAVE4      INTEGER
);

CREATE TABLE USUARIOS (
    CODUSUARIO  INTEGER NOT NULL,
    LOGIN       VARCHAR(15),
    SENHA       VARCHAR(10),
    NOME        VARCHAR(40),
    TIPO        VARCHAR(1),
    PERFIL      VARCHAR(15),
    CODCIDADE   INTEGER
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE LOGUSUARIO ADD CONSTRAINT PK_LOGUSUARIO PRIMARY KEY (SEQ);
ALTER TABLE NCONTADOR ADD CONSTRAINT PK_NCONTADOR PRIMARY KEY (COLUNA);
ALTER TABLE PROGRAMAS ADD CONSTRAINT PK_PROGRAMAS PRIMARY KEY (CODPROGRAMA);
ALTER TABLE PROGRAMASUSUARIO ADD CONSTRAINT PK_PROGRAMASUSUARIO PRIMARY KEY (CODUSUARIO, CODPROGRAMA);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (CODUSUARIO);
